os: linux
dist: xenial
language: node_js
jobs:
  include:
  - os: linux
    node_js: 12
  - os: osx
    node_js: 12
addons:
  chrome: stable
  firefox: latest
services:
- xvfb
script:
- npm run ci
before_deploy:
- sed -i 's/"private":\ true/"private":\ false/' package.json
- sed -i -E 's/^dist\/?.*$//' .gitignore
- cp -r src/* .
deploy:
  provider: npm
  edge: true
  email:
    secure: c/u3dsMFxB/JwNNUa3G+aotltA08al8k4SfpJGe3g3/yiNeDz1YSJw9N+2DK8USWrfDK8YB1cZIFscGbrjD6OU37IKzovZooAcmtDyopRB7dGMeajoFtCT2TtBX38mwp3LNqR84iKRPwLlpV+Lv5qpyzQpaqyzcD5TeKObCd85RdSR3AqkDVi7BgkewRpU3M/J1EXZ6a5VbPky4cskRNbQDK/LPFr8AQflO21bwLkciDgRrPvx5Bbp+w/KXukQIOeMVGnygY/j9M/kesXIPDqXQKGnLxKo0H5hZs4u+74F+JshlS4x3FPBX/NemPpAKTD3fZ3MvQqpMLsYdLF4VUO4FizJkPLOaJB/ZJ+JCPJexbI/duj3BpvhPpp/8MP3n0jCH6w9hLqhRBvLkwDYwY/xp6KVLhvWfdqhMFHwJC1nyLmtBc4OHSNhgdqddYaVOUj1q9xzvWyp/LhsqKNguKSn1EnAar4N/+uJ3kwdOHapQLV1Wxk7KBGfD3vawTzlUlpBRP/yrqgVl7mdCEMuj1xpx4EDy/5HXYlGyvmk1/avKia4KpwCowJzIQzHUSigfOOfnaP0+J74b1OhENeeQ9Gg2VwZ7tw5j2MN5FKnE42d9CilrheRYZNm2D25mFoHosHpgEu1/YyK2//ll6bsTfr2pk6YR+3WfwjCR4kgNGEV0=
  api_token:
    secure: "v8ibYM9jGVQ43620bFTMZ7/kTG2+p8WSEkIkqmPSG9ygw6u21Ta9Cw6dK2b+JYO4cKyDr4lTRzkMn/4x9pHIIgzmiwedMBZ/xBXKjpKgPNhkHMCYdkNAyk05K50b+wDasSEqC8+M4mIgZ6SUbv9hP2taKTNjAQFdZrpxvJPo6khDMNFnFAbK+3+8BQTdUUWsHsHaoTrTdifPXoxT8r37IaLckUot2Av7r6VLLL64Rjnl59SasUsPgDRDfgj8tESfCP0Q2Ja4m2kqEprI3xGaceBw6nUSucCTWgSUEuVFProrMOnStuIS5ium4i7CldPOF/GAngMTi0FuPZj7hnyQziYhf0qrUOumsCCKCScCFSQ/3dRIt3IisAWS9q+JdVnZkBRzzJ/Y5X2y23Zjc+nJuLNBhr0nQBUukXteaFX6dNThv0CxoVQXjZ9zJ30xn1tfQOaOCN1zhjGDoGv1uemOPt1ccTltatLY+M8nRGP/WRW0wsobMVALAWXDBVsMI3Ch7TlzC+i1BgLaxMb4kY0rfJ1X4+1NG82Ay+YOCZhhiHY7hEltF+13BM9B+VjCEjyxJAmGTAzK8X7c034yzl+e0ZPAsssZULvVFX1X0A2MEMtYaEmDjYKYRLUBcrtKhBUfIQJRZ4MTuNuyiYKzpa8H3rFwY+JltOkiCAl5ZT4+4OQ="
  on:
    node_js: 12
    condition:
    - $TRAVIS_BRANCH = master
    - $TRAVIS_EVENT_TYPE = push
    - $TRAVIS_COMMIT_MESSAGE =~ ^v[0-9]+(\.[0-9]+)*($|\n)
    - $TRAVIS_OS_NAME = linux
notifications:
  email:
    recipients:
      secure: c/u3dsMFxB/JwNNUa3G+aotltA08al8k4SfpJGe3g3/yiNeDz1YSJw9N+2DK8USWrfDK8YB1cZIFscGbrjD6OU37IKzovZooAcmtDyopRB7dGMeajoFtCT2TtBX38mwp3LNqR84iKRPwLlpV+Lv5qpyzQpaqyzcD5TeKObCd85RdSR3AqkDVi7BgkewRpU3M/J1EXZ6a5VbPky4cskRNbQDK/LPFr8AQflO21bwLkciDgRrPvx5Bbp+w/KXukQIOeMVGnygY/j9M/kesXIPDqXQKGnLxKo0H5hZs4u+74F+JshlS4x3FPBX/NemPpAKTD3fZ3MvQqpMLsYdLF4VUO4FizJkPLOaJB/ZJ+JCPJexbI/duj3BpvhPpp/8MP3n0jCH6w9hLqhRBvLkwDYwY/xp6KVLhvWfdqhMFHwJC1nyLmtBc4OHSNhgdqddYaVOUj1q9xzvWyp/LhsqKNguKSn1EnAar4N/+uJ3kwdOHapQLV1Wxk7KBGfD3vawTzlUlpBRP/yrqgVl7mdCEMuj1xpx4EDy/5HXYlGyvmk1/avKia4KpwCowJzIQzHUSigfOOfnaP0+J74b1OhENeeQ9Gg2VwZ7tw5j2MN5FKnE42d9CilrheRYZNm2D25mFoHosHpgEu1/YyK2//ll6bsTfr2pk6YR+3WfwjCR4kgNGEV0=
    on_success: change
    on_failure: always
after_script:
- git clean -df
- gulp bench
